services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${PROD_DB_USER}
            POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
            POSTGRES_DB: ${PROD_DB_NAME}
            COMPOSE_PROJECT_NAME: beok
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - beok-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: beok
        image: beok-backend:latest
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: always
        volumes:
            - .:/app
        env_file:
            - .env
              
        ports:
            - 8000:8000
        depends_on:
            - db
        networks:
            - beok-network

volumes:
    postgres_data:

networks:
    beok-network:
        driver: bridge