# Generated by Django 3.2.9 on 2023-03-06 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(blank=True, choices=[('--', '--'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='--', max_length=255, null=True)),
                ('alergies', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.TextField()),
                ('results', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultated_by_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultated_by', to='doctors.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDependentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependent_names', models.CharField(max_length=255)),
                ('dependent_relationship', models.CharField(choices=[('friend', 'Friend'), ('family', 'Family'), ('child', 'Child'), ('spouse', 'Spouse'), ('other', 'Other')], max_length=255)),
                ('dependent_age', models.IntegerField()),
                ('dependent_blood_group', models.CharField(blank=True, max_length=255, null=True)),
                ('dependent_alergies', models.TextField(blank=True, null=True)),
                ('dependent_symptoms', models.TextField()),
                ('dependent_results', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consulted_by_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_consultated_by', to='doctors.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_dependents', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
